# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edmond & Jocelyn
email: 644568491@qq.com
description: > # To record any exicting, impressive and beautiful moment of our life.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://edmondwang.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  EdmondWang
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'